
const requests = {
  registration: `user/register/`,
  login: `token/`,
  refresh: `token/refresh/`,
  logout: `user/logout/blacklist/`,
  userDetails: 'user/get-user-details/',
  editProfile: 'user/edit-user-profile/',
  trainerList: 'v1/trainers-list/',
  trainerDetails: 'v1/get-trainer/',
  ownerDogList: 'v1/users-dog-list/',
  addDog: 'v1/create-dog/',
  userDogList: 'v1/users-dog-list/',
  dogDetails: 'v1/get-update-del-dog/',
  trainerAvailible: 'v1/check_trainer_in_walks/',
  orderAWalk: 'v1/create-walk/',
  getWalks: 'v1/walks-list/',
  getTrainerWalks: 'v1/trainer-walks-list/',
  updateWalk: 'v1/update-walk/',
  getTrainerWorkDaysByUser: 'v1/get-trainer-work-days-by-user/',
  walkDetails: 'v1/trainer-walks-list/',
  dogList: 'v1/get-dog-list/',
  getDog: 'v1/get-dog/',
  getNotificationCount: 'notification/get-notification-count/',
  getNotifications: 'notification/get-notification/',
  getUserWalks: 'v1/walk-list-user/',
  getUserDogsForTrainer: 'v1/users-dog-list-for-trainer/',
  getUserDetailsForTrainer: 'user/get-user/',
}

export default requests;