# Generated by Django 3.2.12 on 2022-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Ocena', 'verbose_name_plural': 'Oceny'},
        ),
    ]
