# Generated by Django 3.2.12 on 2022-05-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rating_options'),
        ('api', '0003_auto_20220506_1529'),
    ]

    operations = [
    ]
