# Generated by Django 3.2.12 on 2022-05-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220506_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Walk',
        ),
    ]
