# Generated by Django 3.2.12 on 2022-05-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20220507_0647'),
        ('api', '0005_walk'),
    ]

    operations = [
    ]
