# Generated by Django 3.2.12 on 2022-05-17 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('walk_start_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Powiadomienia spacery',
                'verbose_name_plural': 'Powiadomienia spacery',
            },
        ),
        migrations.CreateModel(
            name='WalkNotifiCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_displayed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walk_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.walknotification')),
            ],
        ),
        migrations.AddField(
            model_name='walknotification',
            name='targets_ids',
            field=models.ManyToManyField(through='notification.WalkNotifiCustomUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
